repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.1
    hooks:
      - id: stylua-system
        args: [--config-path=.stylua.toml]
        files: ^(lua|after)/.*\.lua$  # Target only Lua files in specific directories

  - repo: local
    hooks:
      - id: check-nvim-config
        name: Check Neovim config
        entry: nvim --headless -c "lua vim.health.report()" -c "qa!"
        language: system
        pass_filenames: false
        always_run: true
