repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.13.1
    hooks:
      - id: stylua-github # stylua / stylua-system / stylua-github
